"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { AnimatePresence, motion } from "framer-motion";
import { Activity, Bell, Bot, CheckSquare2, ChevronLeft, ChevronRight, CircleGauge, FileSearch2, History, Menu, Search, Settings, ShieldAlert, TerminalSquare, X, Zap } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { scenarioList, type ScenarioId } from "../lib/scenarios";
import type { IncidentStatus } from "../lib/types";
import { cn, statusCopy } from "../lib/ui";

export type View = "overview"|"incidents"|"agents"|"evidence"|"approvals"|"actions"|"audit";
const nav = [
  ["overview","Overview",CircleGauge], ["incidents","Incidents",ShieldAlert], ["agents","Agents",Bot],
  ["evidence","Evidence",FileSearch2], ["approvals","Approvals",CheckSquare2], ["actions","Actions",TerminalSquare], ["audit","Audit log",History],
] as const;

export function AppShell({view,onView,status,children,error,onDismiss,onNewIncident,onRunScenario}:{view:View;onView:(view:View)=>void;status:IncidentStatus;children:ReactNode;error:string;onDismiss:()=>void;onNewIncident:()=>void;onRunScenario:(id:ScenarioId)=>void}) {
  const [collapsed,setCollapsed]=useState(false);const [mobile,setMobile]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [settingsOpen,setSettingsOpen]=useState(false);const [notificationsOpen,setNotificationsOpen]=useState(false);const [query,setQuery]=useState("");const [reducedMotion,setReducedMotion]=useState(false);
  useEffect(()=>{const close=()=>setMobile(false);const keys=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true)}};window.addEventListener("resize",close);window.addEventListener("keydown",keys);return()=>{window.removeEventListener("resize",close);window.removeEventListener("keydown",keys)}},[]);
  useEffect(()=>{document.documentElement.classList.toggle("force-reduced-motion",reducedMotion)},[reducedMotion]);
  const results=useMemo(()=>{const value=query.trim().toLowerCase();const views=nav.filter(([,label])=>!value||label.toLowerCase().includes(value));const labs=scenarioList.filter(item=>!value||`${item.title} ${item.service} ${item.region}`.toLowerCase().includes(value));return {views,labs}},[query]);
  const selectView=(next:View)=>{onView(next);setMobile(false);setSearchOpen(false)};
  return <div className="app-root">
    <a href="#main-content" className="skip-link">Skip to content</a>
    <aside className={cn("sidebar",collapsed&&"sidebar-collapsed",mobile&&"sidebar-mobile-open")}>
      <div className="brand-row"><button className="brand" onClick={()=>selectView("overview")} aria-label="Redline overview"><span>R</span><b>REDLINE</b></button><button className="icon-button sidebar-toggle" onClick={()=>setCollapsed(value=>!value)} aria-label={collapsed?"Expand navigation":"Collapse navigation"}>{collapsed?<ChevronRight/>:<ChevronLeft/>}</button></div>
      <nav className="primary-nav" aria-label="Primary navigation">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>selectView(id)} className={cn("nav-item",view===id&&"active")} aria-current={view===id?"page":undefined}><Icon/><span>{label}</span>{id==="incidents"&&status!=="HEALTHY"&&status!=="RESOLVED"&&<i/>}</button>)}</nav>
      <div className="sidebar-footer"><div className="runtime"><span className="runtime-dot"/><div><b>Control plane online</b><small>API · Runtime · Database</small></div></div><button className="nav-item" onClick={()=>setSettingsOpen(true)}><Settings/><span>Settings</span></button><div className="user-row"><span className="avatar">NO</span><div><b>Nadia Okafor</b><small>Incident commander</small></div></div></div>
    </aside>
    <div className={cn("shell-main",collapsed&&"shell-main-wide")}><header className="topbar editorial-topbar"><button className="icon-button mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><button className="topbar-brand" onClick={()=>selectView("overview")} aria-label="Redline overview"><span>R</span><b>REDLINE</b></button><nav className="topbar-nav" aria-label="Primary navigation">{nav.map(([id,label])=><button key={id} onClick={()=>selectView(id)} className={cn(view===id&&"active")} aria-current={view===id?"page":undefined}>{label}</button>)}</nav><button className="search-button" onClick={()=>setSearchOpen(true)}><Search/>Search <kbd>⌘K</kbd></button><div className="topbar-right"><button className="button secondary new-incident" onClick={onNewIncident}><Zap/>New incident</button><span className={cn("status-pill",status.toLowerCase())}>{statusCopy[status]}</span><button className="icon-button" aria-label="Notifications" onClick={()=>setNotificationsOpen(true)}><Bell/></button><span className="avatar small">NO</span></div></header>
      <AnimatePresence>{error&&<motion.div className="error-banner" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0}}><Activity/><span><b>Request failed.</b> {error}</span><button onClick={onDismiss}><X/></button></motion.div>}</AnimatePresence><main id="main-content" className="content">{children}</main></div>{mobile&&<button className="mobile-scrim" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}

    <Dialog.Root open={searchOpen} onOpenChange={setSearchOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="command-dialog"><Dialog.Title>Search Redline</Dialog.Title><div className="command-input"><Search/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search views, incidents, services, or regions" aria-label="Search Redline"/><kbd>ESC</kbd></div><div className="command-results"><span className="command-group">NAVIGATION</span>{results.views.map(([id,label,Icon])=><button key={id} onClick={()=>selectView(id)}><Icon/><span><b>{label}</b><small>Open control-plane view</small></span><ChevronRight/></button>)}<span className="command-group">INCIDENT LABS</span>{results.labs.map(item=><button key={item.id} onClick={()=>{setSearchOpen(false);onRunScenario(item.id)}}><ShieldAlert/><span><b>{item.title}</b><small>{item.service} · {item.region} · {item.severity}</small></span><em>RUN</em></button>)}{results.views.length+results.labs.length===0&&<div className="command-empty">No matching Redline resource.</div>}</div><Dialog.Close className="icon-button command-close" aria-label="Close search"><X/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>

    <Dialog.Root open={settingsOpen} onOpenChange={setSettingsOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="settings-dialog"><div className="dialog-title-row"><div><span className="eyebrow">CONTROL PLANE</span><Dialog.Title>Settings</Dialog.Title></div><Dialog.Close className="icon-button" aria-label="Close settings"><X/></Dialog.Close></div><Dialog.Description>Runtime and interface preferences for this local Redline installation.</Dialog.Description><section><h3>Runtime</h3>{[["Environment","production"],["API","connected"],["Database","SQLite"],["Voice","OpenAI Realtime configured"]].map(([label,value])=><div className="setting-row" key={label}><span>{label}</span><b><i/>{value}</b></div>)}</section><section><h3>Interface</h3><label className="setting-row"><span><b>Reduce animation</b><small>Disable topology motion and transitions</small></span><input type="checkbox" checked={reducedMotion} onChange={event=>setReducedMotion(event.target.checked)}/></label><button className="setting-row setting-button" onClick={()=>{setCollapsed(false);setSettingsOpen(false)}}><span><b>Reset sidebar</b><small>Restore expanded navigation</small></span><ChevronRight/></button></section></Dialog.Content></Dialog.Portal></Dialog.Root>

    <Dialog.Root open={notificationsOpen} onOpenChange={setNotificationsOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="notification-dialog"><div className="dialog-title-row"><Dialog.Title>Notifications</Dialog.Title><Dialog.Close className="icon-button" aria-label="Close notifications"><X/></Dialog.Close></div><div className="notification-item"><span className={cn("notification-dot",status.toLowerCase())}/><div><b>{statusCopy[status]}</b><p>{status==="AWAITING_HUMAN"?"An incident is waiting for your authorization.":status==="RESOLVED"?"Recovery has been verified and the incident is resolved.":"No unacknowledged control-plane alerts."}</p></div></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}
